name: Maven CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  maven_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: maven

      - name: Test with Maven
        run: mvn test

      - name: Upload jacoco results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Jacoco coverage results
          path: target/site/jacoco

      - name: Cache build
        uses: actions/cache@v3
        with:
          key: cached-build-${{ github.sha }}
          path: .

  update_dependence_graph:
    needs: [maven_test]        
    runs-on: ubuntu-latest
    permissions:
      contents: write        

    steps:
      - name: Restore cached build
        uses: actions/cache@v3
        with:
          key: cached-build-${{ github.sha }}
          path: .

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v3
  sonar_scan:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: [maven_test]         
    permissions:
      contents: read             

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Run SonarQube scan
        uses: SonarSource/sonarcloud-github-action@master  # SonarCloud
        with:
          organization: ${{ secrets.SONAR_ORGANIZATION }}  # 仅 SonarCloud
          projectKey: cs1632-cicd-pipelines                   # 你的项目 Key
          projectName: cs1632-cicd-pipelines
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}